apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: serverside
        image: ahmedalmahdi/serverside:latest
        ports:
        - containerPort: 8080
        env:
        - name: ConnectionStrings__DefaultConnection
          value: "Server=svc-sqlserver;Database=AppDb;User Id=sa;Password=MasterKey0;TrustServerCertificate=True;"
        - name: AllowedOrigins
          value: "http://localhost" # we need modify this to fit with the minikube cluster value
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8080
        #   initialDelaySeconds: 10
        #   periodSeconds: 5
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8080
        #   initialDelaySeconds: 15
        #   periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: svc-backend
  namespace: app-namespace
spec:
  ports:
    - port: 8080
  selector:
    app: api
  type: ClusterIP
