apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: clientside
        image: ahmedalmahdi/clientside:latest
        ports:
        - containerPort: 80
        env:
        - name: API_URL
          value: "http://svc-backend:8080/api"
---
apiVersion: v1
kind: Service
metadata:
  name: svc-frontend
  namespace: app-namespace
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000  # You can set any port between 30000-32767, or omit to let Kubernetes choose
  selector:
    app: client

