apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: test
data:
  # API Environment Variables
  ConnectionStrings__DefaultConnection: "Server=svc-sqlserver;Database=AppDb;User Id=sa;Password=MasterKey0;TrustServerCertificate=True;"
  
  AllowedOrigins: "http://svc-frontend:80"

  # Client Environment Variables
  API_URL: "http://svc-backend:8080/api"
