apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: dev
data:
  API_URL: "http://localhost:8080/api"
  VERSION: "v1"
  ConnectionStrings__DefaultConnection: "Server=srv-sqlserver;Database=AppDb;User Id=sa;Password=MasterKey0;TrustServerCertificate=True;"
  AllowedOrigins: "http://localhost"
  ACCEPT_EULA: "Y"
  MSSQL_SA_PASSWORD: "MasterKey0"
