apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: test
data:
  # API Environment Variables
  ConnectionStrings__DefaultConnection: "Server=svc-sqlserver;Database=AppDb;User Id=sa;Password=MasterKey0;TrustServerCertificate=True;"
  AllowedOrigins: "http://192.168.49.2:30000"

  # Client Environment Variables
  API_URL: "http://192.168.49.2:30001/api"
