apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dev
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ahmedalmahdi/serverside:v2
        ports:
        - containerPort: 8080
        env:
          - name: ConnectionStrings__DefaultConnection
            valueFrom:
              secretKeyRef:
                name: global-secrets
                key: db-connection-string
          - name: AllowedOrigins # Critical: Set this correctly!
            value: "*" # Or a specific origin if security is a concern
          - name: API_URL # Not strictly needed in backend itself
            value: "http://svc-backend:8080/api"
          - name: VERSION
            value: "v1" # Or use a ConfigMap if desired
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "750m"
            memory: "1Gi"
        # readinessProbe:  # Add readiness and liveness probes
        #   httpGet:
        #     path: /health  # Replace with your backend health check endpoint
        #     port: 8080
        #   initialDelaySeconds: 10
        #   periodSeconds: 5
        # livenessProbe:
        #   httpGet:
        #     path: /health # Replace with your backend health check endpoint
        #     port: 8080
        #   initialDelaySeconds: 15
        #   periodSeconds: 10
