apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "app.local"  # Replace with your domain/IP
    http:
      paths:
      - path: /frontend
        pathType: Prefix
        backend:
          service:
            name: svc-frontend
            port:
              number: 80
      - path: /backend #  /backend path for backend service
        pathType: Prefix
        backend:
          service:
            name: svc-backend
            port:
              number: 8080