---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver-data-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard  # This uses Minikube's default storage class