apiVersion: v1
kind: Service
metadata:
  name: svc-backend
  namespace: dev
spec:
  selector:  # Removed type: NodePort 
    app: backend # ONLY use the Ingress for external access
  ports:
  - port: 8080  # Internal port
    targetPort: 8080