---
- name: Install dependencies
  hosts: all
  become: yes
  tasks:
    - name: Install Node.js and npm
      apt:
        name:
          - nodejs
          - npm
        state: present
      register: node_install
      until: node_install is success
      retries: 3
      delay: 5

    - name: Install Angular CLI
      npm:
        name: "@angular/cli"
        version: "18.2.7"
        global: yes
      register: angular_install
      until: angular_install is success
      retries: 3
      delay: 5

    - name: Install Chrome
      apt:
        deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      register: chrome_install
      until: chrome_install is success
      retries: 3
      delay: 5